### ISSUE TITLE
Scheme preview broken

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#37]
TypeError: Cannot set property 'projects' of undefined
    at r.$scope.loadScheme (schemeViewModalController.js:12)
    at r.$scope.init (schemeViewModalController.js:7)
    at new <anonymous> (schemeViewModalController.js:41)
    at e (angular.js:4535)
    at Object.instantiate (angular.js:4543)
    at angular.js:9395
    at resolveSuccess (ui-bootstrap-tpls.js:4142)
    at angular.js:14991
    at r.$eval (angular.js:16251)

**Comment by JeannedArk** [comment]
Again broken

angular.js:12722 TypeError: Cannot read property 'length' of undefined
    at r.$scope.loadScheme (schemeViewModalController.js:13)
    at r.$scope.init (schemeViewModalController.js:7)
    at new <anonymous> (schemeViewModalController.js:41)
    at e (angular.js:4535)
    at Object.instantiate (angular.js:4543)
    at angular.js:9395
    at resolveSuccess (ui-bootstrap-tpls.js:4142)
    at angular.js:14991
    at r.$eval (angular.js:16251)
    at r.$digest (angular.js:16069)

**Comment by JeannedArk** [comment]
Done.

**Comment by annefried** [comment]
I am still getting errors the SECOND time I try opening this (a different error). The first time it opens, the second time it doesn't. (on master 5b79d1)

**Comment by annefried** [comment]
Also, please remove this option from the projects view for annotators. The JSON format won't be meaningful to them. We can add this back for annotators once we have integrated a different scheme viewer here, but not for Milestone 1.

**Comment by annefried** [comment]
In the projects view, I also get to see the wrong scheme (not the one assigned with the project).

**Comment by JeannedArk** [comment]
Pull request: https://github.com/annefried/discanno/pull/71

**Comment by annefried** [comment]
fixed in 5268ab, pull request #71
